/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 ./public/models/src/iconYT.glb --output models/4096/IconYT.tsx -r public/models4096 --transform -t --resolution 4096 --keepmaterials -m --keepmeshes --keepnames -s 
Files: ./public/models/src/iconYT.glb [4.05MB] > C:\Users\Tommy\Documents\GitHub\frederic-cartier\models\4096\models/4096/iconYT-transformed.glb [149.7KB] (96%)
*/

import * as THREE from 'three';
import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';
import { GLTF } from 'three-stdlib';
import { useFrame } from '@react-three/fiber';

type GLTFResult = GLTF & {
	nodes: {
		youtube_1: THREE.Mesh;
		youtube_2: THREE.Mesh;
	};
	materials: {
		ytWhite: THREE.MeshStandardMaterial;
	};
	// animations: GLTFAction[]
};

type ContextType = Record<string, React.ForwardRefExoticComponent<JSX.IntrinsicElements['mesh']>>;
const glbURL =
	'https://raw.githubusercontent.com/thomasmatlock/public/main/models/iconYT-transformed.glb';
export function Model(props: JSX.IntrinsicElements['group']) {
	const { nodes, materials } = useGLTF(glbURL) as GLTFResult;
	return (
		<group {...props} dispose={null}>
			<group name="youtube" position={[0.003, 0.91, 0.26]} userData={{ name: 'youtube' }}>
				<mesh
					name="youtube_1"
					castShadow
					receiveShadow
					geometry={nodes.youtube_1.geometry}
					material={materials.ytWhite}
				/>
				<mesh
					name="youtube_2"
					castShadow
					receiveShadow
					geometry={nodes.youtube_2.geometry}
					material={materials.ytWhite}
				/>
			</group>
		</group>
	);
}

useGLTF.preload(glbURL);
